### ISSUE TITLE
Adding Openstack (cloudwatt) VimInstance from dashboard error: Not listed Images successfully of VimInstance

### ISSUE THREAD

**Issue by BediarSofiane** [openbaton/openbaton-client#1]
Hello,
I'm trying to add a VimInstance from the openbaton dashboard (localhost:8080) with a .json file. but i'm getting this exception :

ERROR: HTTP status: 422 response data : {"code":"Bad Request","message":"Not listed Images successfully of VimInstance CloudWatt. Caused by: org.openbaton.exceptions.VimDriverException: p-imgcld-00.usr.prd1.val.cloudwatt.net connecting to GET https://p-imgcld-00.usr.prd1.val.cloudwatt.net:9292/v1/images/detail?limit=1000 HTTP/1.1"}

This is my .json file:
{
  "name":"CloudWatt",
  "authUrl":"THE AUTH LINK",
  "tenant":"THE TENANT NAME",
  "username":"MY_USER_NAME"
  "password":"MY_PASSWORD",
  "keyPair":"THE_KEY",
  "securityGroups": [
        THE SECURITY GROUPS
   ],
  "type":"openstack"
  
  
}
If someone could help me with this or suggest some ideas of what is causing this exception.
Thank you guys.

**Comment by lorenzotomasini** [comment]
I BediarSofiane,

we didn't experience that error before. I see you are using CloudWatt, aren't you? If yes, I don't think the openstack plugin works with CloudWatt. But I'm don't really know much about CloudWatt. If this is the case you should consider create a CloudWatt plugin. It's pretty easy :)

PS. please consider open a issue on the related repo, [here](https://github.com/openbaton/openstack-plugin/issues) for instance

**Comment by BediarSofiane** [comment]
Hi @lorenzotomasini 
Thank you for your answer.
Sorry for the unappropriate repo :(
Yes actually i'm using CloudWatt. Then i'll see how to create a CloudWatt plugin.
Thank you for helping.

**Comment by ftcjeff** [comment]
FWIW - I get the same error when using rackspace as my openstack VIM.

**Comment by gc4rella** [comment]
@ftcjeff just replied you on the issue you opened on the openstack-plugin project. I would keep this issue closed.
